---
# file: main.yml

- name: Deploy AMQ Broker Operator for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'amqbrokeroperator.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: operators

- name: pause
  pause:
    minutes: "3"
  when: operators.changed

# Deploy Artemis Instance for each team
- name: Deploy Artemis for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'artemis.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: artemis

- name: pause
  pause:
    minutes: "3"
  when: artemis.changed

# Create the Address
- name: Create Broker address for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'address.yml.j2') }}"
  loop: "{{ labs_teams }}"
  