---
# file: main.yml

# Deploy AMQ Streams Operator
- name: Deploy AMQ Streams Operator
  k8s:
    namespace: openshift-operators
    state: present
    definition: "{{ lookup('file', 'amqstreamsoperator.yaml') }}"
  register: operator

- name: pause
  pause:
    minutes: "3"
  when: operator.changed

# Deploy Kafka Instance for each team
- name: Deploy kafka instance for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'kafka.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: instances
    
- name: pause
  pause:
    minutes: "3"
  when: instances.changed

# Deploy Kafka topic for each team
- name: Deploy kafka topic for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'topic.yml.j2') }}"
  loop: "{{ labs_teams }}"