---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team1-fuseonlineaccess
  namespace: team1
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: team1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: syndesis-editor