apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: team4-example-address
  namespace: team4
spec:
  addressName: example-address
  queueName: example-queue
  routingType: anycast