---
  # file: main.yml

# Deploy Fuse Online Operator Group 
- name: Deploy Fuse Online Operator Group for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'fuseonlineoperatorgroup.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: operator_groups

# XXX This doesn't do anything useful... the files exist anyway
# - name: Wait for Fuse Online group to be deployed for team1
#   wait_for:
#     path: "{{ role_path }}/files/fuseonlineoperatorgroup1.yaml"
#     state: present

- name: pause
  pause:
    minutes: "3"
  when: operator_groups.changed

# Deploy Fuse Online operator
- name: Deploy Fuse Online for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'fuseonlineoperator.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: fuse_online

- name: pause
  pause:
    minutes: "3"
  when: fuse_online.changed
  
# Create the Fuse Online Syndesis
- name: Create Fuse Online Syndesis for each team
  k8s:
    state: present
    definition: "{{ lookup('template', 'syndesis.yml.j2') }}"
  loop: "{{ labs_teams }}"
  register: syndesis

- name: pause
  pause:
    minutes: "2"
  when: syndesis.changed

# Create group role bindings for Fuse online access
- name: Role binding for team1
  k8s:
    state: present
    definition: "{{ lookup('template', 'fuserolebinding.yml.j2') }}"
  loop: "{{ labs_teams }}"